# If you update this file, please also update _config_netlify.yml with the exact same changes
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
theme: ods-jekyll-theme
baseurl: "/ods-android"
defaults:
  - scope:
      path: ""
    values:
      version: ""
  - scope:
      path: "0.10.0"
    values:
      version: "0.10.0"
  - scope:
      path: "0.11.0"
    values:
      version: "0.11.0"
  - scope:
      path: "0.11.1"
    values:
      version: "0.11.1"
  - scope:
      path: "0.12.0"
    values:
      version: "0.12.0"
  - scope:
      path: "0.13.0"
    values:
      version: "0.13.0"
  - scope:
      path: "0.14.0"
    values:
      version: "0.14.0"
  - scope:
      path: "0.15.0"
    values:
      version: "0.15.0"
  - scope:
      path: "0.15.1"
    values:
      version: "0.15.1"
  - scope:
      path: "0.16.0"
    values:
      version: "0.16.0"
  - scope:
      path: "0.17.0"
    values:
      version: "0.17.0"
  - scope:
      path: "0.18.0"
    values:
      version: "0.18.0"
